# Generated by Django 3.1.4 on 2020-12-21 15:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('keywords', models.CharField(max_length=222)),
                ('description', models.TextField(max_length=255)),
                ('company', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=155)),
                ('phone', models.CharField(blank=True, max_length=155)),
                ('fax', models.CharField(blank=True, max_length=155)),
                ('email', models.CharField(blank=True, max_length=155)),
                ('smtserver', models.CharField(blank=True, max_length=155)),
                ('smtemail', models.CharField(blank=True, max_length=155)),
                ('smtpassword', models.CharField(blank=True, max_length=155)),
                ('smtport', models.CharField(blank=True, max_length=155)),
                ('icon', models.ImageField(blank=True, upload_to='media/images/')),
                ('facebook', models.CharField(blank=True, max_length=155)),
                ('instagram', models.CharField(blank=True, max_length=155)),
                ('twitter', models.CharField(blank=True, max_length=155)),
                ('youtube', models.CharField(blank=True, max_length=155)),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('status', models.CharField(choices=[('True', 'Mavjud'), ('False', 'Mavjud emas')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
